[ProfileToolBar] bugfix for eventfilter missing plot attribute
Define `plot` attribute prior to calling `qt.QToolBar __init__`, in the hope it will fix the CI test failure (Python 3.5, Qt5, Qt tests enabled) related to the `eventFilter` called before plot is defined..

```
testAlignedProfile (silx.gui.plot.test.testProfile.TestProfileToolBar)
Test horizontal and vertical profile, without and with image ... Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\Profile.py", line 451, in eventFilter
    self.clearProfile()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\Profile.py", line 551, in clearProfile
    self.updateProfile()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\Profile.py", line 558, in updateProfile
    imageData = self.plot.getActiveImage()
AttributeError: 'ProfileToolBar' object has no attribute 'plot'
```